version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker from Jenkins container
    environment:
      DOCKER_TLS_VERIFY: "1"
      DOCKER_HOST: "tcp://docker:2376"
  
  chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}

volumes:
  jenkins_home:
